/**
 * @file llmachineid.cpp
 * @brief retrieves unique machine ids via Windows registry MachineGuid
 *
 * $LicenseInfo:firstyear=2009&license=viewerlgpl$
 * Second Life Viewer Source Code
 * Copyright (C) 2010, Linden Research, Inc.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation;
 * version 2.1 of the License only.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 * Linden Research, Inc., 945 Battery Street, San Francisco, CA  94111  USA
 * $/LicenseInfo$
 */

#include "llviewerprecompiledheaders.h"
#include "lluuid.h"
#include "llmachineid.h"

#include <iostream>
#include <iomanip>
#include <string>
#include <cstring>

#include <windows.h>


unsigned char static_unique_id[] = { 0,0,0,0,0,0 };
unsigned char static_legacy_id[] = { 0,0,0,0,0,0 };
bool static has_static_unique_id = false;
bool static has_static_legacy_id = false;


// Derive a 6-byte digest from the wide-character MachineGuid string by XOR-folding
// each character into the output buffer.  The MachineGuid is a stable per-machine
// UUID generated by Windows at install time (HKLM\SOFTWARE\Microsoft\Cryptography).
static void derive_digest(const std::wstring& guid, unsigned char* digest, size_t len)
{
    memset(digest, 0, len);
    for (size_t i = 0; i < guid.size(); ++i)
    {
        digest[i % len] ^= static_cast<unsigned char>(guid[i]);
    }
}


S32 LLMachineID::init()
{
    size_t len = sizeof(static_unique_id);
    memset(static_unique_id, 0, len);
    memset(static_legacy_id, 0, len);
    S32 ret_code = 0;

    HKEY hKey = nullptr;
    LONG result = RegOpenKeyExW(
        HKEY_LOCAL_MACHINE,
        L"SOFTWARE\\Microsoft\\Cryptography",
        0,
        KEY_READ | KEY_WOW64_64KEY,
        &hKey);

    if (result == ERROR_SUCCESS)
    {
        wchar_t machineGuid[64] = { 0 };
        DWORD size = sizeof(machineGuid);
        result = RegQueryValueExW(hKey, L"MachineGuid", nullptr, nullptr,
                                  reinterpret_cast<LPBYTE>(machineGuid), &size);

        if (result == ERROR_SUCCESS && size > sizeof(wchar_t))
        {
            std::wstring guid(machineGuid);
            derive_digest(guid, static_unique_id, len);
            derive_digest(guid, static_legacy_id, len);

            has_static_unique_id = true;
            LL_DEBUGS("AppInit") << "Using MachineGuid as unique id" << LL_ENDL;
        }
        RegCloseKey(hKey);
    }

    if (!has_static_unique_id)
    {
        // Fallback: generate from MAC address (same as the original legacy code path)
        unsigned char* staticPtr = reinterpret_cast<unsigned char*>(&static_unique_id[0]);
        ret_code = LLUUID::getNodeID(staticPtr);
        memcpy(static_legacy_id, static_unique_id, len);
        has_static_unique_id = true;
        has_static_legacy_id = false;
        LL_DEBUGS("AppInit") << "Using MAC address as fallback unique id" << LL_ENDL;
        return ret_code;
    }

    unsigned char* staticPtr = reinterpret_cast<unsigned char*>(&static_unique_id[0]);
    ret_code = LLUUID::getNodeID(staticPtr);
    has_static_unique_id = true;
    has_static_legacy_id = false;

    LL_INFOS("AppInit") << "UniqueID: 0x";
    for (size_t i = 0; i < len; ++i)
    {
        unsigned byte = static_unique_id[i];
        LL_CONT << std::hex << std::setw(2) << std::setfill('0') << byte;
    }
    LL_CONT << std::dec << std::setw(0) << std::setfill(' ') << LL_ENDL;

    return ret_code;
}


S32 LLMachineID::getUniqueID(unsigned char* unique_id, size_t len)
{
    if (has_static_unique_id)
    {
        memcpy(unique_id, &static_unique_id, len);
        return 1;
    }
    return 0;
}


S32 LLMachineID::getLegacyID(unsigned char* unique_id, size_t len)
{
    if (has_static_legacy_id)
    {
        memcpy(unique_id, &static_legacy_id, len);
        return 1;
    }
    return 0;
}
